/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TtsTestRouteImport } from './routes/tts-test'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SttShadowRouteImport } from './routes/stt-shadow'
import { Route as SignupCodeRouteImport } from './routes/signup-code'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as QrStatsRouteImport } from './routes/qr-stats'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameIndexRouteImport } from './routes/game/index'
import { Route as GameVocashotIndexRouteImport } from './routes/game/vocashot/index'
import { Route as GameContentIndexRouteImport } from './routes/game/content/index'
import { Route as GameVocashotCreateRouteImport } from './routes/game/vocashot/create'
import { Route as GameContentGameRouteImport } from './routes/game/content/$game'
import { Route as GameVocashotHostPinRouteImport } from './routes/game/vocashot/host.$pin'

const TtsTestRoute = TtsTestRouteImport.update({
  id: '/tts-test',
  path: '/tts-test',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SttShadowRoute = SttShadowRouteImport.update({
  id: '/stt-shadow',
  path: '/stt-shadow',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupCodeRoute = SignupCodeRouteImport.update({
  id: '/signup-code',
  path: '/signup-code',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const QrStatsRoute = QrStatsRouteImport.update({
  id: '/qr-stats',
  path: '/qr-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameVocashotIndexRoute = GameVocashotIndexRouteImport.update({
  id: '/game/vocashot/',
  path: '/game/vocashot/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameContentIndexRoute = GameContentIndexRouteImport.update({
  id: '/game/content/',
  path: '/game/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameVocashotCreateRoute = GameVocashotCreateRouteImport.update({
  id: '/game/vocashot/create',
  path: '/game/vocashot/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GameContentGameRoute = GameContentGameRouteImport.update({
  id: '/game/content/$game',
  path: '/game/content/$game',
  getParentRoute: () => rootRouteImport,
} as any)
const GameVocashotHostPinRoute = GameVocashotHostPinRouteImport.update({
  id: '/game/vocashot/host/$pin',
  path: '/game/vocashot/host/$pin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/qr-stats': typeof QrStatsRoute
  '/school': typeof SchoolRoute
  '/signup': typeof SignupRoute
  '/signup-code': typeof SignupCodeRoute
  '/stt-shadow': typeof SttShadowRoute
  '/student': typeof StudentRoute
  '/tts-test': typeof TtsTestRoute
  '/game/': typeof GameIndexRoute
  '/game/content/$game': typeof GameContentGameRoute
  '/game/vocashot/create': typeof GameVocashotCreateRoute
  '/game/content/': typeof GameContentIndexRoute
  '/game/vocashot/': typeof GameVocashotIndexRoute
  '/game/vocashot/host/$pin': typeof GameVocashotHostPinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/qr-stats': typeof QrStatsRoute
  '/school': typeof SchoolRoute
  '/signup': typeof SignupRoute
  '/signup-code': typeof SignupCodeRoute
  '/stt-shadow': typeof SttShadowRoute
  '/student': typeof StudentRoute
  '/tts-test': typeof TtsTestRoute
  '/game': typeof GameIndexRoute
  '/game/content/$game': typeof GameContentGameRoute
  '/game/vocashot/create': typeof GameVocashotCreateRoute
  '/game/content': typeof GameContentIndexRoute
  '/game/vocashot': typeof GameVocashotIndexRoute
  '/game/vocashot/host/$pin': typeof GameVocashotHostPinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/qr-stats': typeof QrStatsRoute
  '/school': typeof SchoolRoute
  '/signup': typeof SignupRoute
  '/signup-code': typeof SignupCodeRoute
  '/stt-shadow': typeof SttShadowRoute
  '/student': typeof StudentRoute
  '/tts-test': typeof TtsTestRoute
  '/game/': typeof GameIndexRoute
  '/game/content/$game': typeof GameContentGameRoute
  '/game/vocashot/create': typeof GameVocashotCreateRoute
  '/game/content/': typeof GameContentIndexRoute
  '/game/vocashot/': typeof GameVocashotIndexRoute
  '/game/vocashot/host/$pin': typeof GameVocashotHostPinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/qr-stats'
    | '/school'
    | '/signup'
    | '/signup-code'
    | '/stt-shadow'
    | '/student'
    | '/tts-test'
    | '/game/'
    | '/game/content/$game'
    | '/game/vocashot/create'
    | '/game/content/'
    | '/game/vocashot/'
    | '/game/vocashot/host/$pin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/qr-stats'
    | '/school'
    | '/signup'
    | '/signup-code'
    | '/stt-shadow'
    | '/student'
    | '/tts-test'
    | '/game'
    | '/game/content/$game'
    | '/game/vocashot/create'
    | '/game/content'
    | '/game/vocashot'
    | '/game/vocashot/host/$pin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/qr-stats'
    | '/school'
    | '/signup'
    | '/signup-code'
    | '/stt-shadow'
    | '/student'
    | '/tts-test'
    | '/game/'
    | '/game/content/$game'
    | '/game/vocashot/create'
    | '/game/content/'
    | '/game/vocashot/'
    | '/game/vocashot/host/$pin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  QrStatsRoute: typeof QrStatsRoute
  SchoolRoute: typeof SchoolRoute
  SignupRoute: typeof SignupRoute
  SignupCodeRoute: typeof SignupCodeRoute
  SttShadowRoute: typeof SttShadowRoute
  StudentRoute: typeof StudentRoute
  TtsTestRoute: typeof TtsTestRoute
  GameIndexRoute: typeof GameIndexRoute
  GameContentGameRoute: typeof GameContentGameRoute
  GameVocashotCreateRoute: typeof GameVocashotCreateRoute
  GameContentIndexRoute: typeof GameContentIndexRoute
  GameVocashotIndexRoute: typeof GameVocashotIndexRoute
  GameVocashotHostPinRoute: typeof GameVocashotHostPinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tts-test': {
      id: '/tts-test'
      path: '/tts-test'
      fullPath: '/tts-test'
      preLoaderRoute: typeof TtsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stt-shadow': {
      id: '/stt-shadow'
      path: '/stt-shadow'
      fullPath: '/stt-shadow'
      preLoaderRoute: typeof SttShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-code': {
      id: '/signup-code'
      path: '/signup-code'
      fullPath: '/signup-code'
      preLoaderRoute: typeof SignupCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-stats': {
      id: '/qr-stats'
      path: '/qr-stats'
      fullPath: '/qr-stats'
      preLoaderRoute: typeof QrStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/vocashot/': {
      id: '/game/vocashot/'
      path: '/game/vocashot'
      fullPath: '/game/vocashot/'
      preLoaderRoute: typeof GameVocashotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/content/': {
      id: '/game/content/'
      path: '/game/content'
      fullPath: '/game/content/'
      preLoaderRoute: typeof GameContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/vocashot/create': {
      id: '/game/vocashot/create'
      path: '/game/vocashot/create'
      fullPath: '/game/vocashot/create'
      preLoaderRoute: typeof GameVocashotCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/content/$game': {
      id: '/game/content/$game'
      path: '/game/content/$game'
      fullPath: '/game/content/$game'
      preLoaderRoute: typeof GameContentGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/vocashot/host/$pin': {
      id: '/game/vocashot/host/$pin'
      path: '/game/vocashot/host/$pin'
      fullPath: '/game/vocashot/host/$pin'
      preLoaderRoute: typeof GameVocashotHostPinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  QrStatsRoute: QrStatsRoute,
  SchoolRoute: SchoolRoute,
  SignupRoute: SignupRoute,
  SignupCodeRoute: SignupCodeRoute,
  SttShadowRoute: SttShadowRoute,
  StudentRoute: StudentRoute,
  TtsTestRoute: TtsTestRoute,
  GameIndexRoute: GameIndexRoute,
  GameContentGameRoute: GameContentGameRoute,
  GameVocashotCreateRoute: GameVocashotCreateRoute,
  GameContentIndexRoute: GameContentIndexRoute,
  GameVocashotIndexRoute: GameVocashotIndexRoute,
  GameVocashotHostPinRoute: GameVocashotHostPinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
