"""
콘텐츠별 총 문제 수.
키: (book_id, chapter_seq), 값: { menu_type: count }
tools/convert_textbook_xlsx.py 가 교재기반 콘텐츠 엑셀에서 자동 생성 — 직접 수정하지 말 것.
"""

TOTAL_QUESTIONS = {
    (1, 4): {"word": 9, "roleplay": 2, "listen-answer": 3, "fill-blank": 6, "read-answer": 5},
    (1, 5): {"word": 9, "roleplay": 2, "listen-answer": 5, "fill-blank": 6, "read-answer": 4},
    (1, 6): {"word": 10, "roleplay": 2, "listen-answer": 4, "fill-blank": 5, "read-answer": 5},
    (1, 7): {"word": 8, "roleplay": 2, "listen-answer": 4, "fill-blank": 6, "read-answer": 5},
    (1, 8): {"word": 9, "roleplay": 2, "listen-answer": 5, "fill-blank": 6, "read-answer": 5},
    (1, 9): {"word": 10, "roleplay": 2, "listen-answer": 5, "fill-blank": 7, "read-answer": 5},
    (1, 10): {"word": 10, "roleplay": 2, "listen-answer": 4, "fill-blank": 8, "read-answer": 6},
    (1, 11): {"word": 9, "roleplay": 2, "listen-answer": 5, "fill-blank": 4, "read-answer": 5},
    (1, 12): {"word": 10, "roleplay": 2, "listen-answer": 4, "fill-blank": 6, "read-answer": 5},
    (1, 13): {"word": 10, "roleplay": 2, "listen-answer": 4, "fill-blank": 4, "read-answer": 5},
    (1, 14): {"word": 10, "roleplay": 2, "listen-answer": 5, "fill-blank": 6, "read-answer": 5},
    (1, 15): {"word": 10, "roleplay": 2, "listen-answer": 4, "fill-blank": 6, "read-answer": 5},
    (2, 1): {"word": 10, "roleplay": 2, "listen-answer": 5, "fill-blank": 9, "read-answer": 4},
    (2, 2): {"word": 9, "roleplay": 2, "listen-answer": 6, "fill-blank": 9, "read-answer": 3},
    (2, 3): {"word": 9, "roleplay": 2, "listen-answer": 5, "fill-blank": 10, "read-answer": 4},
    (2, 4): {"word": 10, "roleplay": 2, "listen-answer": 5, "fill-blank": 9, "read-answer": 2},
    (2, 5): {"word": 10, "roleplay": 2, "listen-answer": 4, "fill-blank": 9, "read-answer": 4},
    (2, 6): {"word": 10, "roleplay": 2, "listen-answer": 4, "fill-blank": 7, "read-answer": 3},
    (2, 7): {"word": 10, "roleplay": 2, "listen-answer": 5, "fill-blank": 10, "read-answer": 4},
    (2, 8): {"word": 10, "roleplay": 2, "listen-answer": 6, "fill-blank": 9, "read-answer": 3},
    (2, 9): {"word": 10, "roleplay": 2, "listen-answer": 5, "fill-blank": 10, "read-answer": 3},
    (2, 10): {"word": 10, "roleplay": 2, "listen-answer": 4, "fill-blank": 10, "read-answer": 3},
    (2, 11): {"word": 10, "roleplay": 2, "listen-answer": 5, "fill-blank": 10, "read-answer": 4},
    (2, 12): {"word": 8, "roleplay": 2, "listen-answer": 5, "fill-blank": 9, "read-answer": 3},
    (2, 13): {"word": 10, "roleplay": 2, "listen-answer": 5, "fill-blank": 9, "read-answer": 4},
    (2, 14): {"word": 10, "roleplay": 2, "listen-answer": 5, "fill-blank": 8, "read-answer": 4},
    (2, 15): {"word": 10, "roleplay": 2, "listen-answer": 5, "fill-blank": 8, "read-answer": 4},
    (3, 1): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 4},
    (3, 2): {"word": 10, "roleplay": 1, "listen-answer": 8, "fill-blank": 7, "read-answer": 2},
    (3, 3): {"word": 10, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (3, 4): {"word": 10, "roleplay": 1, "listen-answer": 6, "fill-blank": 7, "read-answer": 4},
    (3, 5): {"word": 10, "roleplay": 1, "listen-answer": 9, "fill-blank": 7, "read-answer": 4},
    (3, 6): {"word": 9, "roleplay": 1, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (3, 7): {"word": 10, "roleplay": 1, "listen-answer": 9, "fill-blank": 7, "read-answer": 3},
    (3, 8): {"word": 10, "roleplay": 1, "listen-answer": 8, "fill-blank": 7, "read-answer": 3},
    (3, 9): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 4},
    (3, 10): {"word": 10, "roleplay": 1, "listen-answer": 8, "fill-blank": 7},
    (3, 11): {"word": 9, "roleplay": 1, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (3, 12): {"word": 10, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 4},
    (3, 13): {"word": 10, "roleplay": 1, "listen-answer": 6, "fill-blank": 7, "read-answer": 1},
    (3, 14): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 5},
    (3, 15): {"word": 10, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (4, 1): {"word": 7, "roleplay": 1, "listen-answer": 9, "fill-blank": 7, "read-answer": 3},
    (4, 2): {"word": 10, "roleplay": 2, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (4, 3): {"word": 10, "roleplay": 1, "listen-answer": 8, "fill-blank": 7, "read-answer": 3},
    (4, 4): {"word": 10, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (4, 5): {"word": 8, "roleplay": 1, "listen-answer": 9, "fill-blank": 7, "read-answer": 3},
    (4, 6): {"word": 10, "roleplay": 1, "listen-answer": 8, "fill-blank": 7, "read-answer": 3},
    (4, 7): {"word": 10, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (4, 8): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (4, 9): {"word": 10, "roleplay": 2, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (4, 10): {"word": 10, "roleplay": 2, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (4, 11): {"word": 10, "roleplay": 1, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (4, 12): {"word": 10, "roleplay": 2, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (4, 13): {"word": 10, "roleplay": 2, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (4, 14): {"word": 10, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (4, 15): {"word": 10, "roleplay": 2, "listen-answer": 8, "fill-blank": 7, "read-answer": 3},
    (5, 1): {"word": 10, "roleplay": 2, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (5, 2): {"word": 10, "roleplay": 2, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (5, 3): {"word": 10, "roleplay": 2, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (5, 4): {"word": 10, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (5, 5): {"word": 10, "roleplay": 1, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (5, 6): {"word": 10, "roleplay": 2, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (5, 7): {"word": 10, "roleplay": 2, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (5, 8): {"word": 10, "roleplay": 1, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (5, 9): {"word": 10, "roleplay": 1, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (5, 10): {"word": 10, "roleplay": 2, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (5, 11): {"word": 10, "roleplay": 2, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (5, 12): {"word": 10, "roleplay": 1, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (5, 13): {"word": 10, "roleplay": 1, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (5, 14): {"word": 10, "roleplay": 1, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (5, 15): {"word": 10, "roleplay": 2, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (6, 1): {"word": 9, "roleplay": 1, "listen-answer": 4, "fill-blank": 7, "read-answer": 3},
    (6, 2): {"word": 10, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (6, 3): {"word": 10, "roleplay": 1, "listen-answer": 9, "fill-blank": 7, "read-answer": 3},
    (6, 4): {"word": 10, "roleplay": 1, "listen-answer": 3, "fill-blank": 7, "read-answer": 3},
    (6, 5): {"word": 10, "roleplay": 1, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (6, 6): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (6, 7): {"word": 10, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (6, 8): {"word": 10, "roleplay": 1, "listen-answer": 9, "fill-blank": 7, "read-answer": 3},
    (6, 9): {"word": 10, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (6, 10): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (6, 11): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (6, 12): {"word": 10, "roleplay": 1, "listen-answer": 4, "fill-blank": 7, "read-answer": 3},
    (6, 13): {"word": 10, "roleplay": 1, "listen-answer": 4, "fill-blank": 7, "read-answer": 3},
    (6, 14): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (6, 15): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (7, 1): {"word": 10, "roleplay": 1, "listen-answer": 8, "fill-blank": 7, "read-answer": 3},
    (7, 2): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (7, 3): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (7, 4): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (7, 5): {"word": 10, "roleplay": 1, "listen-answer": 4, "fill-blank": 7, "read-answer": 3},
    (7, 6): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (7, 7): {"word": 10, "roleplay": 1, "listen-answer": 4, "fill-blank": 7, "read-answer": 3},
    (7, 8): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (7, 9): {"word": 10, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (7, 10): {"word": 10, "roleplay": 2, "listen-answer": 4, "fill-blank": 7, "read-answer": 3},
    (7, 11): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (7, 12): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (7, 13): {"word": 10, "roleplay": 1, "listen-answer": 4, "fill-blank": 7, "read-answer": 3},
    (7, 14): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (7, 15): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (8, 1): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (8, 2): {"word": 9, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (8, 3): {"word": 10, "roleplay": 1, "listen-answer": 5, "fill-blank": 7, "read-answer": 3},
    (8, 4): {"word": 10, "roleplay": 1, "listen-answer": 4, "fill-blank": 7, "read-answer": 3},
    (8, 5): {"word": 10, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (8, 6): {"word": 10, "roleplay": 1, "listen-answer": 9, "fill-blank": 7, "read-answer": 3},
    (8, 7): {"word": 10, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (8, 8): {"word": 10, "roleplay": 1, "listen-answer": 6, "fill-blank": 7, "read-answer": 3},
    (8, 9): {"word": 10, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (8, 10): {"word": 10, "roleplay": 1, "listen-answer": 4, "fill-blank": 7, "read-answer": 3},
    (8, 11): {"word": 9, "roleplay": 2, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (8, 12): {"word": 10, "roleplay": 1, "listen-answer": 4, "fill-blank": 7, "read-answer": 3},
    (8, 13): {"word": 10, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (8, 14): {"word": 9, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
    (8, 15): {"word": 10, "roleplay": 1, "listen-answer": 7, "fill-blank": 7, "read-answer": 3},
}

MODULE_LABELS = {
    "word": "단어 학습하기",
    "roleplay": "AI 롤플레잉",
    "listen-answer": "듣고 질문에 답하기",
    "fill-blank": "빈칸 채워 말하기",
    "read-answer": "읽고 질문에 답하기",
    "mission-chat": "AI 미션 대화",
    "flashcard": "단어 플래시카드",
}

LEARN_ROUTES = {
    "word": "/learn/word",
    "roleplay": "/learn/roleplay",
    "listen-answer": "/learn/listen-answer",
    "fill-blank": "/learn/fill-blank",
    "read-answer": "/learn/read-answer",
    "mission-chat": "/book/chapter/unit/mission_chat",
    "flashcard": "/book/chapter/unit/flashcard",
}


def getTotalQuestionCount():
    """전체 콘텐츠 총 문제 수"""
    total = 0
    for counts in TOTAL_QUESTIONS.values():
        total += sum(counts.values())
    return total


def getChapterQuestionCount(bookId: int, chapterSeq: int) -> int:
    """특정 과의 총 문제 수"""
    counts = TOTAL_QUESTIONS.get((bookId, chapterSeq), {})
    return sum(counts.values())
