/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as FlashcardRouteImport } from './routes/flashcard'
import { Route as JamolistRouteImport } from './routes/jamolist'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MainRouteImport } from './routes/main'
import { Route as MissionchatRouteImport } from './routes/missionchat'
import { Route as MyPasswordRouteImport } from './routes/my-password'
import { Route as MyProfileRouteImport } from './routes/my-profile'
import { Route as NewPasswordRouteImport } from './routes/new-password'
import { Route as QrRouteImport } from './routes/qr'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as BookIndexRouteImport } from './routes/book/index'
import { Route as BookIdRouteImport } from './routes/book/$id'
import { Route as BookListRouteImport } from './routes/book/list'
import { Route as LearnFillBlankRouteImport } from './routes/learn/fill-blank'
import { Route as LearnGrammarRouteImport } from './routes/learn/grammar'
import { Route as LearnListenRouteImport } from './routes/learn/listen'
import { Route as LearnListenAnswerRouteImport } from './routes/learn/listen-answer'
import { Route as LearnReadRouteImport } from './routes/learn/read'
import { Route as LearnReadAnswerRouteImport } from './routes/learn/read-answer'
import { Route as LearnRoleplayRouteImport } from './routes/learn/roleplay'
import { Route as LearnWordRouteImport } from './routes/learn/word'
import { Route as MainIndexRouteImport } from './routes/main/index'
import { Route as MainClipRouteImport } from './routes/main/clip'
import { Route as MainGameRouteImport } from './routes/main/game'
import { Route as MainMyRouteImport } from './routes/main/my'
import { Route as MainTextbookRouteImport } from './routes/main/textbook'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as TestIdRouteImport } from './routes/test/$id'
import { Route as TestAudioRouteImport } from './routes/test/audio'
import { Route as TestBoomRouteImport } from './routes/test/boom'
import { Route as TestDebugRouteImport } from './routes/test/debug'
import { Route as TestFlashcardRouteImport } from './routes/test/flashcard'
import { Route as TestRealtimeRouteImport } from './routes/test/realtime'
import { Route as TestTtsRegenRouteImport } from './routes/test/tts-regen'
import { Route as TestVideosRouteImport } from './routes/test/videos'
import { Route as BookChapterIdRouteImport } from './routes/book/chapter/$id'
import { Route as LearnJamoChooseRouteImport } from './routes/learn/jamo/choose'
import { Route as LearnJamoCombineRouteImport } from './routes/learn/jamo/combine'
import { Route as LearnJamoCombine3RouteImport } from './routes/learn/jamo/combine3'
import { Route as LearnJamoPronounceRouteImport } from './routes/learn/jamo/pronounce'
import { Route as LearnJamoWordRepeatRouteImport } from './routes/learn/jamo/word-repeat'
import { Route as LearnJamoWordWriteRouteImport } from './routes/learn/jamo/word-write'
import { Route as MainGameIndexRouteImport } from './routes/main/game/index'
import { Route as MainGameCardSortRouteImport } from './routes/main/game/card-sort'
import { Route as MainGameMissionchatRouteImport } from './routes/main/game/missionchat'
import { Route as MainGameParticleSniperRouteImport } from './routes/main/game/particle-sniper'
import { Route as MainGameSeoulPuzzleRouteImport } from './routes/main/game/seoul-puzzle'
import { Route as MainGameSpringPicnicRouteImport } from './routes/main/game/spring-picnic'
import { Route as MainGameVocashotRouteImport } from './routes/main/game/vocashot'
import { Route as MainGameVocashotSoloRouteImport } from './routes/main/game/vocashot-solo'
import { Route as MainTextbookIndexRouteImport } from './routes/main/textbook/index'
import { Route as MainTextbookJamoRouteImport } from './routes/main/textbook/jamo'
import { Route as BookChapterUnitIdRouteImport } from './routes/book/chapter/unit/$id'
import { Route as MainGameVocashotPinRouteImport } from './routes/main/game/vocashot_.$pin'
import { Route as BookChapterUnitDialogIdRouteImport } from './routes/book/chapter/unit/dialog/$id'
import { Route as BookChapterUnitFlashcardIdRouteImport } from './routes/book/chapter/unit/flashcard/$id'
import { Route as BookChapterUnitInput_wordCodeRouteImport } from './routes/book/chapter/unit/input_word/$code'
import { Route as BookChapterUnitListenRepeatCodeRouteImport } from './routes/book/chapter/unit/listen-repeat/$code'
import { Route as BookChapterUnitListenRepeat2CodeRouteImport } from './routes/book/chapter/unit/listen-repeat2/$code'
import { Route as BookChapterUnitListenCodeRouteImport } from './routes/book/chapter/unit/listen/$code'
import { Route as BookChapterUnitMake_sentenceCodeRouteImport } from './routes/book/chapter/unit/make_sentence/$code'
import { Route as BookChapterUnitMission_chatCodeRouteImport } from './routes/book/chapter/unit/mission_chat/$code'
import { Route as BookChapterUnitReadWriteCodeRouteImport } from './routes/book/chapter/unit/read-write/$code'
import { Route as BookChapterUnitWriteCodeRouteImport } from './routes/book/chapter/unit/write/$code'
import { Route as BookChapterUnitWrite2CodeRouteImport } from './routes/book/chapter/unit/write2/$code'
import { Route as BookChapterUnitWrite3CodeRouteImport } from './routes/book/chapter/unit/write3/$code'
import { Route as BookChapterUnitDialogReportIdRouteImport } from './routes/book/chapter/unit/dialog/report/$id'
import { Route as BookChapterUnitFlashcardResultIdRouteImport } from './routes/book/chapter/unit/flashcard/result/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardRoute = FlashcardRouteImport.update({
  id: '/flashcard',
  path: '/flashcard',
  getParentRoute: () => rootRouteImport,
} as any)
const JamolistRoute = JamolistRouteImport.update({
  id: '/jamolist',
  path: '/jamolist',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionchatRoute = MissionchatRouteImport.update({
  id: '/missionchat',
  path: '/missionchat',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPasswordRoute = MyPasswordRouteImport.update({
  id: '/my-password',
  path: '/my-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPasswordRoute = NewPasswordRouteImport.update({
  id: '/new-password',
  path: '/new-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookListRoute = BookListRouteImport.update({
  id: '/book/list',
  path: '/book/list',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnFillBlankRoute = LearnFillBlankRouteImport.update({
  id: '/learn/fill-blank',
  path: '/learn/fill-blank',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnGrammarRoute = LearnGrammarRouteImport.update({
  id: '/learn/grammar',
  path: '/learn/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnListenRoute = LearnListenRouteImport.update({
  id: '/learn/listen',
  path: '/learn/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnListenAnswerRoute = LearnListenAnswerRouteImport.update({
  id: '/learn/listen-answer',
  path: '/learn/listen-answer',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnReadRoute = LearnReadRouteImport.update({
  id: '/learn/read',
  path: '/learn/read',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnReadAnswerRoute = LearnReadAnswerRouteImport.update({
  id: '/learn/read-answer',
  path: '/learn/read-answer',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoleplayRoute = LearnRoleplayRouteImport.update({
  id: '/learn/roleplay',
  path: '/learn/roleplay',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnWordRoute = LearnWordRouteImport.update({
  id: '/learn/word',
  path: '/learn/word',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainClipRoute = MainClipRouteImport.update({
  id: '/clip',
  path: '/clip',
  getParentRoute: () => MainRoute,
} as any)
const MainGameRoute = MainGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => MainRoute,
} as any)
const MainMyRoute = MainMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => MainRoute,
} as any)
const MainTextbookRoute = MainTextbookRouteImport.update({
  id: '/textbook',
  path: '/textbook',
  getParentRoute: () => MainRoute,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIdRoute = TestIdRouteImport.update({
  id: '/test/$id',
  path: '/test/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TestAudioRoute = TestAudioRouteImport.update({
  id: '/test/audio',
  path: '/test/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const TestBoomRoute = TestBoomRouteImport.update({
  id: '/test/boom',
  path: '/test/boom',
  getParentRoute: () => rootRouteImport,
} as any)
const TestDebugRoute = TestDebugRouteImport.update({
  id: '/test/debug',
  path: '/test/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const TestFlashcardRoute = TestFlashcardRouteImport.update({
  id: '/test/flashcard',
  path: '/test/flashcard',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRealtimeRoute = TestRealtimeRouteImport.update({
  id: '/test/realtime',
  path: '/test/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTtsRegenRoute = TestTtsRegenRouteImport.update({
  id: '/test/tts-regen',
  path: '/test/tts-regen',
  getParentRoute: () => rootRouteImport,
} as any)
const TestVideosRoute = TestVideosRouteImport.update({
  id: '/test/videos',
  path: '/test/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const BookChapterIdRoute = BookChapterIdRouteImport.update({
  id: '/book/chapter/$id',
  path: '/book/chapter/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnJamoChooseRoute = LearnJamoChooseRouteImport.update({
  id: '/learn/jamo/choose',
  path: '/learn/jamo/choose',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnJamoCombineRoute = LearnJamoCombineRouteImport.update({
  id: '/learn/jamo/combine',
  path: '/learn/jamo/combine',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnJamoCombine3Route = LearnJamoCombine3RouteImport.update({
  id: '/learn/jamo/combine3',
  path: '/learn/jamo/combine3',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnJamoPronounceRoute = LearnJamoPronounceRouteImport.update({
  id: '/learn/jamo/pronounce',
  path: '/learn/jamo/pronounce',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnJamoWordRepeatRoute = LearnJamoWordRepeatRouteImport.update({
  id: '/learn/jamo/word-repeat',
  path: '/learn/jamo/word-repeat',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnJamoWordWriteRoute = LearnJamoWordWriteRouteImport.update({
  id: '/learn/jamo/word-write',
  path: '/learn/jamo/word-write',
  getParentRoute: () => rootRouteImport,
} as any)
const MainGameIndexRoute = MainGameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainGameRoute,
} as any)
const MainGameCardSortRoute = MainGameCardSortRouteImport.update({
  id: '/card-sort',
  path: '/card-sort',
  getParentRoute: () => MainGameRoute,
} as any)
const MainGameMissionchatRoute = MainGameMissionchatRouteImport.update({
  id: '/missionchat',
  path: '/missionchat',
  getParentRoute: () => MainGameRoute,
} as any)
const MainGameParticleSniperRoute = MainGameParticleSniperRouteImport.update({
  id: '/particle-sniper',
  path: '/particle-sniper',
  getParentRoute: () => MainGameRoute,
} as any)
const MainGameSeoulPuzzleRoute = MainGameSeoulPuzzleRouteImport.update({
  id: '/seoul-puzzle',
  path: '/seoul-puzzle',
  getParentRoute: () => MainGameRoute,
} as any)
const MainGameSpringPicnicRoute = MainGameSpringPicnicRouteImport.update({
  id: '/spring-picnic',
  path: '/spring-picnic',
  getParentRoute: () => MainGameRoute,
} as any)
const MainGameVocashotRoute = MainGameVocashotRouteImport.update({
  id: '/vocashot',
  path: '/vocashot',
  getParentRoute: () => MainGameRoute,
} as any)
const MainGameVocashotSoloRoute = MainGameVocashotSoloRouteImport.update({
  id: '/vocashot-solo',
  path: '/vocashot-solo',
  getParentRoute: () => MainGameRoute,
} as any)
const MainTextbookIndexRoute = MainTextbookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainTextbookRoute,
} as any)
const MainTextbookJamoRoute = MainTextbookJamoRouteImport.update({
  id: '/jamo',
  path: '/jamo',
  getParentRoute: () => MainTextbookRoute,
} as any)
const BookChapterUnitIdRoute = BookChapterUnitIdRouteImport.update({
  id: '/book/chapter/unit/$id',
  path: '/book/chapter/unit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MainGameVocashotPinRoute = MainGameVocashotPinRouteImport.update({
  id: '/vocashot_/$pin',
  path: '/vocashot/$pin',
  getParentRoute: () => MainGameRoute,
} as any)
const BookChapterUnitDialogIdRoute = BookChapterUnitDialogIdRouteImport.update({
  id: '/book/chapter/unit/dialog/$id',
  path: '/book/chapter/unit/dialog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookChapterUnitFlashcardIdRoute =
  BookChapterUnitFlashcardIdRouteImport.update({
    id: '/book/chapter/unit/flashcard/$id',
    path: '/book/chapter/unit/flashcard/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookChapterUnitInput_wordCodeRoute =
  BookChapterUnitInput_wordCodeRouteImport.update({
    id: '/book/chapter/unit/input_word/$code',
    path: '/book/chapter/unit/input_word/$code',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookChapterUnitListenRepeatCodeRoute =
  BookChapterUnitListenRepeatCodeRouteImport.update({
    id: '/book/chapter/unit/listen-repeat/$code',
    path: '/book/chapter/unit/listen-repeat/$code',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookChapterUnitListenRepeat2CodeRoute =
  BookChapterUnitListenRepeat2CodeRouteImport.update({
    id: '/book/chapter/unit/listen-repeat2/$code',
    path: '/book/chapter/unit/listen-repeat2/$code',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookChapterUnitListenCodeRoute =
  BookChapterUnitListenCodeRouteImport.update({
    id: '/book/chapter/unit/listen/$code',
    path: '/book/chapter/unit/listen/$code',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookChapterUnitMake_sentenceCodeRoute =
  BookChapterUnitMake_sentenceCodeRouteImport.update({
    id: '/book/chapter/unit/make_sentence/$code',
    path: '/book/chapter/unit/make_sentence/$code',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookChapterUnitMission_chatCodeRoute =
  BookChapterUnitMission_chatCodeRouteImport.update({
    id: '/book/chapter/unit/mission_chat/$code',
    path: '/book/chapter/unit/mission_chat/$code',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookChapterUnitReadWriteCodeRoute =
  BookChapterUnitReadWriteCodeRouteImport.update({
    id: '/book/chapter/unit/read-write/$code',
    path: '/book/chapter/unit/read-write/$code',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookChapterUnitWriteCodeRoute =
  BookChapterUnitWriteCodeRouteImport.update({
    id: '/book/chapter/unit/write/$code',
    path: '/book/chapter/unit/write/$code',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookChapterUnitWrite2CodeRoute =
  BookChapterUnitWrite2CodeRouteImport.update({
    id: '/book/chapter/unit/write2/$code',
    path: '/book/chapter/unit/write2/$code',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookChapterUnitWrite3CodeRoute =
  BookChapterUnitWrite3CodeRouteImport.update({
    id: '/book/chapter/unit/write3/$code',
    path: '/book/chapter/unit/write3/$code',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookChapterUnitDialogReportIdRoute =
  BookChapterUnitDialogReportIdRouteImport.update({
    id: '/book/chapter/unit/dialog/report/$id',
    path: '/book/chapter/unit/dialog/report/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookChapterUnitFlashcardResultIdRoute =
  BookChapterUnitFlashcardResultIdRouteImport.update({
    id: '/book/chapter/unit/flashcard/result/$id',
    path: '/book/chapter/unit/flashcard/result/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/check-email': typeof CheckEmailRoute
  '/flashcard': typeof FlashcardRoute
  '/jamolist': typeof JamolistRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRouteWithChildren
  '/missionchat': typeof MissionchatRoute
  '/my-password': typeof MyPasswordRoute
  '/my-profile': typeof MyProfileRoute
  '/new-password': typeof NewPasswordRoute
  '/qr': typeof QrRoute
  '/reset-password': typeof ResetPasswordRoute
  '/book/$id': typeof BookIdRoute
  '/book/list': typeof BookListRoute
  '/learn/fill-blank': typeof LearnFillBlankRoute
  '/learn/grammar': typeof LearnGrammarRoute
  '/learn/listen': typeof LearnListenRoute
  '/learn/listen-answer': typeof LearnListenAnswerRoute
  '/learn/read': typeof LearnReadRoute
  '/learn/read-answer': typeof LearnReadAnswerRoute
  '/learn/roleplay': typeof LearnRoleplayRoute
  '/learn/word': typeof LearnWordRoute
  '/main/clip': typeof MainClipRoute
  '/main/game': typeof MainGameRouteWithChildren
  '/main/my': typeof MainMyRoute
  '/main/textbook': typeof MainTextbookRouteWithChildren
  '/test/$id': typeof TestIdRoute
  '/test/audio': typeof TestAudioRoute
  '/test/boom': typeof TestBoomRoute
  '/test/debug': typeof TestDebugRoute
  '/test/flashcard': typeof TestFlashcardRoute
  '/test/realtime': typeof TestRealtimeRoute
  '/test/tts-regen': typeof TestTtsRegenRoute
  '/test/videos': typeof TestVideosRoute
  '/book/': typeof BookIndexRoute
  '/main/': typeof MainIndexRoute
  '/test/': typeof TestIndexRoute
  '/book/chapter/$id': typeof BookChapterIdRoute
  '/learn/jamo/choose': typeof LearnJamoChooseRoute
  '/learn/jamo/combine': typeof LearnJamoCombineRoute
  '/learn/jamo/combine3': typeof LearnJamoCombine3Route
  '/learn/jamo/pronounce': typeof LearnJamoPronounceRoute
  '/learn/jamo/word-repeat': typeof LearnJamoWordRepeatRoute
  '/learn/jamo/word-write': typeof LearnJamoWordWriteRoute
  '/main/game/card-sort': typeof MainGameCardSortRoute
  '/main/game/missionchat': typeof MainGameMissionchatRoute
  '/main/game/particle-sniper': typeof MainGameParticleSniperRoute
  '/main/game/seoul-puzzle': typeof MainGameSeoulPuzzleRoute
  '/main/game/spring-picnic': typeof MainGameSpringPicnicRoute
  '/main/game/vocashot': typeof MainGameVocashotRoute
  '/main/game/vocashot-solo': typeof MainGameVocashotSoloRoute
  '/main/textbook/jamo': typeof MainTextbookJamoRoute
  '/main/game/': typeof MainGameIndexRoute
  '/main/textbook/': typeof MainTextbookIndexRoute
  '/book/chapter/unit/$id': typeof BookChapterUnitIdRoute
  '/main/game/vocashot/$pin': typeof MainGameVocashotPinRoute
  '/book/chapter/unit/dialog/$id': typeof BookChapterUnitDialogIdRoute
  '/book/chapter/unit/flashcard/$id': typeof BookChapterUnitFlashcardIdRoute
  '/book/chapter/unit/input_word/$code': typeof BookChapterUnitInput_wordCodeRoute
  '/book/chapter/unit/listen-repeat/$code': typeof BookChapterUnitListenRepeatCodeRoute
  '/book/chapter/unit/listen-repeat2/$code': typeof BookChapterUnitListenRepeat2CodeRoute
  '/book/chapter/unit/listen/$code': typeof BookChapterUnitListenCodeRoute
  '/book/chapter/unit/make_sentence/$code': typeof BookChapterUnitMake_sentenceCodeRoute
  '/book/chapter/unit/mission_chat/$code': typeof BookChapterUnitMission_chatCodeRoute
  '/book/chapter/unit/read-write/$code': typeof BookChapterUnitReadWriteCodeRoute
  '/book/chapter/unit/write/$code': typeof BookChapterUnitWriteCodeRoute
  '/book/chapter/unit/write2/$code': typeof BookChapterUnitWrite2CodeRoute
  '/book/chapter/unit/write3/$code': typeof BookChapterUnitWrite3CodeRoute
  '/book/chapter/unit/dialog/report/$id': typeof BookChapterUnitDialogReportIdRoute
  '/book/chapter/unit/flashcard/result/$id': typeof BookChapterUnitFlashcardResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/check-email': typeof CheckEmailRoute
  '/flashcard': typeof FlashcardRoute
  '/jamolist': typeof JamolistRoute
  '/login': typeof LoginRoute
  '/missionchat': typeof MissionchatRoute
  '/my-password': typeof MyPasswordRoute
  '/my-profile': typeof MyProfileRoute
  '/new-password': typeof NewPasswordRoute
  '/qr': typeof QrRoute
  '/reset-password': typeof ResetPasswordRoute
  '/book/$id': typeof BookIdRoute
  '/book/list': typeof BookListRoute
  '/learn/fill-blank': typeof LearnFillBlankRoute
  '/learn/grammar': typeof LearnGrammarRoute
  '/learn/listen': typeof LearnListenRoute
  '/learn/listen-answer': typeof LearnListenAnswerRoute
  '/learn/read': typeof LearnReadRoute
  '/learn/read-answer': typeof LearnReadAnswerRoute
  '/learn/roleplay': typeof LearnRoleplayRoute
  '/learn/word': typeof LearnWordRoute
  '/main/clip': typeof MainClipRoute
  '/main/my': typeof MainMyRoute
  '/test/$id': typeof TestIdRoute
  '/test/audio': typeof TestAudioRoute
  '/test/boom': typeof TestBoomRoute
  '/test/debug': typeof TestDebugRoute
  '/test/flashcard': typeof TestFlashcardRoute
  '/test/realtime': typeof TestRealtimeRoute
  '/test/tts-regen': typeof TestTtsRegenRoute
  '/test/videos': typeof TestVideosRoute
  '/book': typeof BookIndexRoute
  '/main': typeof MainIndexRoute
  '/test': typeof TestIndexRoute
  '/book/chapter/$id': typeof BookChapterIdRoute
  '/learn/jamo/choose': typeof LearnJamoChooseRoute
  '/learn/jamo/combine': typeof LearnJamoCombineRoute
  '/learn/jamo/combine3': typeof LearnJamoCombine3Route
  '/learn/jamo/pronounce': typeof LearnJamoPronounceRoute
  '/learn/jamo/word-repeat': typeof LearnJamoWordRepeatRoute
  '/learn/jamo/word-write': typeof LearnJamoWordWriteRoute
  '/main/game/card-sort': typeof MainGameCardSortRoute
  '/main/game/missionchat': typeof MainGameMissionchatRoute
  '/main/game/particle-sniper': typeof MainGameParticleSniperRoute
  '/main/game/seoul-puzzle': typeof MainGameSeoulPuzzleRoute
  '/main/game/spring-picnic': typeof MainGameSpringPicnicRoute
  '/main/game/vocashot': typeof MainGameVocashotRoute
  '/main/game/vocashot-solo': typeof MainGameVocashotSoloRoute
  '/main/textbook/jamo': typeof MainTextbookJamoRoute
  '/main/game': typeof MainGameIndexRoute
  '/main/textbook': typeof MainTextbookIndexRoute
  '/book/chapter/unit/$id': typeof BookChapterUnitIdRoute
  '/main/game/vocashot/$pin': typeof MainGameVocashotPinRoute
  '/book/chapter/unit/dialog/$id': typeof BookChapterUnitDialogIdRoute
  '/book/chapter/unit/flashcard/$id': typeof BookChapterUnitFlashcardIdRoute
  '/book/chapter/unit/input_word/$code': typeof BookChapterUnitInput_wordCodeRoute
  '/book/chapter/unit/listen-repeat/$code': typeof BookChapterUnitListenRepeatCodeRoute
  '/book/chapter/unit/listen-repeat2/$code': typeof BookChapterUnitListenRepeat2CodeRoute
  '/book/chapter/unit/listen/$code': typeof BookChapterUnitListenCodeRoute
  '/book/chapter/unit/make_sentence/$code': typeof BookChapterUnitMake_sentenceCodeRoute
  '/book/chapter/unit/mission_chat/$code': typeof BookChapterUnitMission_chatCodeRoute
  '/book/chapter/unit/read-write/$code': typeof BookChapterUnitReadWriteCodeRoute
  '/book/chapter/unit/write/$code': typeof BookChapterUnitWriteCodeRoute
  '/book/chapter/unit/write2/$code': typeof BookChapterUnitWrite2CodeRoute
  '/book/chapter/unit/write3/$code': typeof BookChapterUnitWrite3CodeRoute
  '/book/chapter/unit/dialog/report/$id': typeof BookChapterUnitDialogReportIdRoute
  '/book/chapter/unit/flashcard/result/$id': typeof BookChapterUnitFlashcardResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/check-email': typeof CheckEmailRoute
  '/flashcard': typeof FlashcardRoute
  '/jamolist': typeof JamolistRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRouteWithChildren
  '/missionchat': typeof MissionchatRoute
  '/my-password': typeof MyPasswordRoute
  '/my-profile': typeof MyProfileRoute
  '/new-password': typeof NewPasswordRoute
  '/qr': typeof QrRoute
  '/reset-password': typeof ResetPasswordRoute
  '/book/$id': typeof BookIdRoute
  '/book/list': typeof BookListRoute
  '/learn/fill-blank': typeof LearnFillBlankRoute
  '/learn/grammar': typeof LearnGrammarRoute
  '/learn/listen': typeof LearnListenRoute
  '/learn/listen-answer': typeof LearnListenAnswerRoute
  '/learn/read': typeof LearnReadRoute
  '/learn/read-answer': typeof LearnReadAnswerRoute
  '/learn/roleplay': typeof LearnRoleplayRoute
  '/learn/word': typeof LearnWordRoute
  '/main/clip': typeof MainClipRoute
  '/main/game': typeof MainGameRouteWithChildren
  '/main/my': typeof MainMyRoute
  '/main/textbook': typeof MainTextbookRouteWithChildren
  '/test/$id': typeof TestIdRoute
  '/test/audio': typeof TestAudioRoute
  '/test/boom': typeof TestBoomRoute
  '/test/debug': typeof TestDebugRoute
  '/test/flashcard': typeof TestFlashcardRoute
  '/test/realtime': typeof TestRealtimeRoute
  '/test/tts-regen': typeof TestTtsRegenRoute
  '/test/videos': typeof TestVideosRoute
  '/book/': typeof BookIndexRoute
  '/main/': typeof MainIndexRoute
  '/test/': typeof TestIndexRoute
  '/book/chapter/$id': typeof BookChapterIdRoute
  '/learn/jamo/choose': typeof LearnJamoChooseRoute
  '/learn/jamo/combine': typeof LearnJamoCombineRoute
  '/learn/jamo/combine3': typeof LearnJamoCombine3Route
  '/learn/jamo/pronounce': typeof LearnJamoPronounceRoute
  '/learn/jamo/word-repeat': typeof LearnJamoWordRepeatRoute
  '/learn/jamo/word-write': typeof LearnJamoWordWriteRoute
  '/main/game/card-sort': typeof MainGameCardSortRoute
  '/main/game/missionchat': typeof MainGameMissionchatRoute
  '/main/game/particle-sniper': typeof MainGameParticleSniperRoute
  '/main/game/seoul-puzzle': typeof MainGameSeoulPuzzleRoute
  '/main/game/spring-picnic': typeof MainGameSpringPicnicRoute
  '/main/game/vocashot': typeof MainGameVocashotRoute
  '/main/game/vocashot-solo': typeof MainGameVocashotSoloRoute
  '/main/textbook/jamo': typeof MainTextbookJamoRoute
  '/main/game/': typeof MainGameIndexRoute
  '/main/textbook/': typeof MainTextbookIndexRoute
  '/book/chapter/unit/$id': typeof BookChapterUnitIdRoute
  '/main/game/vocashot_/$pin': typeof MainGameVocashotPinRoute
  '/book/chapter/unit/dialog/$id': typeof BookChapterUnitDialogIdRoute
  '/book/chapter/unit/flashcard/$id': typeof BookChapterUnitFlashcardIdRoute
  '/book/chapter/unit/input_word/$code': typeof BookChapterUnitInput_wordCodeRoute
  '/book/chapter/unit/listen-repeat/$code': typeof BookChapterUnitListenRepeatCodeRoute
  '/book/chapter/unit/listen-repeat2/$code': typeof BookChapterUnitListenRepeat2CodeRoute
  '/book/chapter/unit/listen/$code': typeof BookChapterUnitListenCodeRoute
  '/book/chapter/unit/make_sentence/$code': typeof BookChapterUnitMake_sentenceCodeRoute
  '/book/chapter/unit/mission_chat/$code': typeof BookChapterUnitMission_chatCodeRoute
  '/book/chapter/unit/read-write/$code': typeof BookChapterUnitReadWriteCodeRoute
  '/book/chapter/unit/write/$code': typeof BookChapterUnitWriteCodeRoute
  '/book/chapter/unit/write2/$code': typeof BookChapterUnitWrite2CodeRoute
  '/book/chapter/unit/write3/$code': typeof BookChapterUnitWrite3CodeRoute
  '/book/chapter/unit/dialog/report/$id': typeof BookChapterUnitDialogReportIdRoute
  '/book/chapter/unit/flashcard/result/$id': typeof BookChapterUnitFlashcardResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/check-email'
    | '/flashcard'
    | '/jamolist'
    | '/login'
    | '/main'
    | '/missionchat'
    | '/my-password'
    | '/my-profile'
    | '/new-password'
    | '/qr'
    | '/reset-password'
    | '/book/$id'
    | '/book/list'
    | '/learn/fill-blank'
    | '/learn/grammar'
    | '/learn/listen'
    | '/learn/listen-answer'
    | '/learn/read'
    | '/learn/read-answer'
    | '/learn/roleplay'
    | '/learn/word'
    | '/main/clip'
    | '/main/game'
    | '/main/my'
    | '/main/textbook'
    | '/test/$id'
    | '/test/audio'
    | '/test/boom'
    | '/test/debug'
    | '/test/flashcard'
    | '/test/realtime'
    | '/test/tts-regen'
    | '/test/videos'
    | '/book/'
    | '/main/'
    | '/test/'
    | '/book/chapter/$id'
    | '/learn/jamo/choose'
    | '/learn/jamo/combine'
    | '/learn/jamo/combine3'
    | '/learn/jamo/pronounce'
    | '/learn/jamo/word-repeat'
    | '/learn/jamo/word-write'
    | '/main/game/card-sort'
    | '/main/game/missionchat'
    | '/main/game/particle-sniper'
    | '/main/game/seoul-puzzle'
    | '/main/game/spring-picnic'
    | '/main/game/vocashot'
    | '/main/game/vocashot-solo'
    | '/main/textbook/jamo'
    | '/main/game/'
    | '/main/textbook/'
    | '/book/chapter/unit/$id'
    | '/main/game/vocashot/$pin'
    | '/book/chapter/unit/dialog/$id'
    | '/book/chapter/unit/flashcard/$id'
    | '/book/chapter/unit/input_word/$code'
    | '/book/chapter/unit/listen-repeat/$code'
    | '/book/chapter/unit/listen-repeat2/$code'
    | '/book/chapter/unit/listen/$code'
    | '/book/chapter/unit/make_sentence/$code'
    | '/book/chapter/unit/mission_chat/$code'
    | '/book/chapter/unit/read-write/$code'
    | '/book/chapter/unit/write/$code'
    | '/book/chapter/unit/write2/$code'
    | '/book/chapter/unit/write3/$code'
    | '/book/chapter/unit/dialog/report/$id'
    | '/book/chapter/unit/flashcard/result/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/check-email'
    | '/flashcard'
    | '/jamolist'
    | '/login'
    | '/missionchat'
    | '/my-password'
    | '/my-profile'
    | '/new-password'
    | '/qr'
    | '/reset-password'
    | '/book/$id'
    | '/book/list'
    | '/learn/fill-blank'
    | '/learn/grammar'
    | '/learn/listen'
    | '/learn/listen-answer'
    | '/learn/read'
    | '/learn/read-answer'
    | '/learn/roleplay'
    | '/learn/word'
    | '/main/clip'
    | '/main/my'
    | '/test/$id'
    | '/test/audio'
    | '/test/boom'
    | '/test/debug'
    | '/test/flashcard'
    | '/test/realtime'
    | '/test/tts-regen'
    | '/test/videos'
    | '/book'
    | '/main'
    | '/test'
    | '/book/chapter/$id'
    | '/learn/jamo/choose'
    | '/learn/jamo/combine'
    | '/learn/jamo/combine3'
    | '/learn/jamo/pronounce'
    | '/learn/jamo/word-repeat'
    | '/learn/jamo/word-write'
    | '/main/game/card-sort'
    | '/main/game/missionchat'
    | '/main/game/particle-sniper'
    | '/main/game/seoul-puzzle'
    | '/main/game/spring-picnic'
    | '/main/game/vocashot'
    | '/main/game/vocashot-solo'
    | '/main/textbook/jamo'
    | '/main/game'
    | '/main/textbook'
    | '/book/chapter/unit/$id'
    | '/main/game/vocashot/$pin'
    | '/book/chapter/unit/dialog/$id'
    | '/book/chapter/unit/flashcard/$id'
    | '/book/chapter/unit/input_word/$code'
    | '/book/chapter/unit/listen-repeat/$code'
    | '/book/chapter/unit/listen-repeat2/$code'
    | '/book/chapter/unit/listen/$code'
    | '/book/chapter/unit/make_sentence/$code'
    | '/book/chapter/unit/mission_chat/$code'
    | '/book/chapter/unit/read-write/$code'
    | '/book/chapter/unit/write/$code'
    | '/book/chapter/unit/write2/$code'
    | '/book/chapter/unit/write3/$code'
    | '/book/chapter/unit/dialog/report/$id'
    | '/book/chapter/unit/flashcard/result/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/check-email'
    | '/flashcard'
    | '/jamolist'
    | '/login'
    | '/main'
    | '/missionchat'
    | '/my-password'
    | '/my-profile'
    | '/new-password'
    | '/qr'
    | '/reset-password'
    | '/book/$id'
    | '/book/list'
    | '/learn/fill-blank'
    | '/learn/grammar'
    | '/learn/listen'
    | '/learn/listen-answer'
    | '/learn/read'
    | '/learn/read-answer'
    | '/learn/roleplay'
    | '/learn/word'
    | '/main/clip'
    | '/main/game'
    | '/main/my'
    | '/main/textbook'
    | '/test/$id'
    | '/test/audio'
    | '/test/boom'
    | '/test/debug'
    | '/test/flashcard'
    | '/test/realtime'
    | '/test/tts-regen'
    | '/test/videos'
    | '/book/'
    | '/main/'
    | '/test/'
    | '/book/chapter/$id'
    | '/learn/jamo/choose'
    | '/learn/jamo/combine'
    | '/learn/jamo/combine3'
    | '/learn/jamo/pronounce'
    | '/learn/jamo/word-repeat'
    | '/learn/jamo/word-write'
    | '/main/game/card-sort'
    | '/main/game/missionchat'
    | '/main/game/particle-sniper'
    | '/main/game/seoul-puzzle'
    | '/main/game/spring-picnic'
    | '/main/game/vocashot'
    | '/main/game/vocashot-solo'
    | '/main/textbook/jamo'
    | '/main/game/'
    | '/main/textbook/'
    | '/book/chapter/unit/$id'
    | '/main/game/vocashot_/$pin'
    | '/book/chapter/unit/dialog/$id'
    | '/book/chapter/unit/flashcard/$id'
    | '/book/chapter/unit/input_word/$code'
    | '/book/chapter/unit/listen-repeat/$code'
    | '/book/chapter/unit/listen-repeat2/$code'
    | '/book/chapter/unit/listen/$code'
    | '/book/chapter/unit/make_sentence/$code'
    | '/book/chapter/unit/mission_chat/$code'
    | '/book/chapter/unit/read-write/$code'
    | '/book/chapter/unit/write/$code'
    | '/book/chapter/unit/write2/$code'
    | '/book/chapter/unit/write3/$code'
    | '/book/chapter/unit/dialog/report/$id'
    | '/book/chapter/unit/flashcard/result/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CheckEmailRoute: typeof CheckEmailRoute
  FlashcardRoute: typeof FlashcardRoute
  JamolistRoute: typeof JamolistRoute
  LoginRoute: typeof LoginRoute
  MainRoute: typeof MainRouteWithChildren
  MissionchatRoute: typeof MissionchatRoute
  MyPasswordRoute: typeof MyPasswordRoute
  MyProfileRoute: typeof MyProfileRoute
  NewPasswordRoute: typeof NewPasswordRoute
  QrRoute: typeof QrRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  BookIdRoute: typeof BookIdRoute
  BookListRoute: typeof BookListRoute
  LearnFillBlankRoute: typeof LearnFillBlankRoute
  LearnGrammarRoute: typeof LearnGrammarRoute
  LearnListenRoute: typeof LearnListenRoute
  LearnListenAnswerRoute: typeof LearnListenAnswerRoute
  LearnReadRoute: typeof LearnReadRoute
  LearnReadAnswerRoute: typeof LearnReadAnswerRoute
  LearnRoleplayRoute: typeof LearnRoleplayRoute
  LearnWordRoute: typeof LearnWordRoute
  TestIdRoute: typeof TestIdRoute
  TestAudioRoute: typeof TestAudioRoute
  TestBoomRoute: typeof TestBoomRoute
  TestDebugRoute: typeof TestDebugRoute
  TestFlashcardRoute: typeof TestFlashcardRoute
  TestRealtimeRoute: typeof TestRealtimeRoute
  TestTtsRegenRoute: typeof TestTtsRegenRoute
  TestVideosRoute: typeof TestVideosRoute
  BookIndexRoute: typeof BookIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  BookChapterIdRoute: typeof BookChapterIdRoute
  LearnJamoChooseRoute: typeof LearnJamoChooseRoute
  LearnJamoCombineRoute: typeof LearnJamoCombineRoute
  LearnJamoCombine3Route: typeof LearnJamoCombine3Route
  LearnJamoPronounceRoute: typeof LearnJamoPronounceRoute
  LearnJamoWordRepeatRoute: typeof LearnJamoWordRepeatRoute
  LearnJamoWordWriteRoute: typeof LearnJamoWordWriteRoute
  BookChapterUnitIdRoute: typeof BookChapterUnitIdRoute
  BookChapterUnitDialogIdRoute: typeof BookChapterUnitDialogIdRoute
  BookChapterUnitFlashcardIdRoute: typeof BookChapterUnitFlashcardIdRoute
  BookChapterUnitInput_wordCodeRoute: typeof BookChapterUnitInput_wordCodeRoute
  BookChapterUnitListenRepeatCodeRoute: typeof BookChapterUnitListenRepeatCodeRoute
  BookChapterUnitListenRepeat2CodeRoute: typeof BookChapterUnitListenRepeat2CodeRoute
  BookChapterUnitListenCodeRoute: typeof BookChapterUnitListenCodeRoute
  BookChapterUnitMake_sentenceCodeRoute: typeof BookChapterUnitMake_sentenceCodeRoute
  BookChapterUnitMission_chatCodeRoute: typeof BookChapterUnitMission_chatCodeRoute
  BookChapterUnitReadWriteCodeRoute: typeof BookChapterUnitReadWriteCodeRoute
  BookChapterUnitWriteCodeRoute: typeof BookChapterUnitWriteCodeRoute
  BookChapterUnitWrite2CodeRoute: typeof BookChapterUnitWrite2CodeRoute
  BookChapterUnitWrite3CodeRoute: typeof BookChapterUnitWrite3CodeRoute
  BookChapterUnitDialogReportIdRoute: typeof BookChapterUnitDialogReportIdRoute
  BookChapterUnitFlashcardResultIdRoute: typeof BookChapterUnitFlashcardResultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcard': {
      id: '/flashcard'
      path: '/flashcard'
      fullPath: '/flashcard'
      preLoaderRoute: typeof FlashcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jamolist': {
      id: '/jamolist'
      path: '/jamolist'
      fullPath: '/jamolist'
      preLoaderRoute: typeof JamolistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missionchat': {
      id: '/missionchat'
      path: '/missionchat'
      fullPath: '/missionchat'
      preLoaderRoute: typeof MissionchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-password': {
      id: '/my-password'
      path: '/my-password'
      fullPath: '/my-password'
      preLoaderRoute: typeof MyPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-profile': {
      id: '/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-password': {
      id: '/new-password'
      path: '/new-password'
      fullPath: '/new-password'
      preLoaderRoute: typeof NewPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/list': {
      id: '/book/list'
      path: '/book/list'
      fullPath: '/book/list'
      preLoaderRoute: typeof BookListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/fill-blank': {
      id: '/learn/fill-blank'
      path: '/learn/fill-blank'
      fullPath: '/learn/fill-blank'
      preLoaderRoute: typeof LearnFillBlankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/grammar': {
      id: '/learn/grammar'
      path: '/learn/grammar'
      fullPath: '/learn/grammar'
      preLoaderRoute: typeof LearnGrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/listen': {
      id: '/learn/listen'
      path: '/learn/listen'
      fullPath: '/learn/listen'
      preLoaderRoute: typeof LearnListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/listen-answer': {
      id: '/learn/listen-answer'
      path: '/learn/listen-answer'
      fullPath: '/learn/listen-answer'
      preLoaderRoute: typeof LearnListenAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/read': {
      id: '/learn/read'
      path: '/learn/read'
      fullPath: '/learn/read'
      preLoaderRoute: typeof LearnReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/read-answer': {
      id: '/learn/read-answer'
      path: '/learn/read-answer'
      fullPath: '/learn/read-answer'
      preLoaderRoute: typeof LearnReadAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/roleplay': {
      id: '/learn/roleplay'
      path: '/learn/roleplay'
      fullPath: '/learn/roleplay'
      preLoaderRoute: typeof LearnRoleplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/word': {
      id: '/learn/word'
      path: '/learn/word'
      fullPath: '/learn/word'
      preLoaderRoute: typeof LearnWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/': {
      id: '/main/'
      path: '/'
      fullPath: '/main/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/clip': {
      id: '/main/clip'
      path: '/clip'
      fullPath: '/main/clip'
      preLoaderRoute: typeof MainClipRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/game': {
      id: '/main/game'
      path: '/game'
      fullPath: '/main/game'
      preLoaderRoute: typeof MainGameRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/my': {
      id: '/main/my'
      path: '/my'
      fullPath: '/main/my'
      preLoaderRoute: typeof MainMyRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/textbook': {
      id: '/main/textbook'
      path: '/textbook'
      fullPath: '/main/textbook'
      preLoaderRoute: typeof MainTextbookRouteImport
      parentRoute: typeof MainRoute
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$id': {
      id: '/test/$id'
      path: '/test/$id'
      fullPath: '/test/$id'
      preLoaderRoute: typeof TestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/audio': {
      id: '/test/audio'
      path: '/test/audio'
      fullPath: '/test/audio'
      preLoaderRoute: typeof TestAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/boom': {
      id: '/test/boom'
      path: '/test/boom'
      fullPath: '/test/boom'
      preLoaderRoute: typeof TestBoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/debug': {
      id: '/test/debug'
      path: '/test/debug'
      fullPath: '/test/debug'
      preLoaderRoute: typeof TestDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/flashcard': {
      id: '/test/flashcard'
      path: '/test/flashcard'
      fullPath: '/test/flashcard'
      preLoaderRoute: typeof TestFlashcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/realtime': {
      id: '/test/realtime'
      path: '/test/realtime'
      fullPath: '/test/realtime'
      preLoaderRoute: typeof TestRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/tts-regen': {
      id: '/test/tts-regen'
      path: '/test/tts-regen'
      fullPath: '/test/tts-regen'
      preLoaderRoute: typeof TestTtsRegenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/videos': {
      id: '/test/videos'
      path: '/test/videos'
      fullPath: '/test/videos'
      preLoaderRoute: typeof TestVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/chapter/$id': {
      id: '/book/chapter/$id'
      path: '/book/chapter/$id'
      fullPath: '/book/chapter/$id'
      preLoaderRoute: typeof BookChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/jamo/choose': {
      id: '/learn/jamo/choose'
      path: '/learn/jamo/choose'
      fullPath: '/learn/jamo/choose'
      preLoaderRoute: typeof LearnJamoChooseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/jamo/combine': {
      id: '/learn/jamo/combine'
      path: '/learn/jamo/combine'
      fullPath: '/learn/jamo/combine'
      preLoaderRoute: typeof LearnJamoCombineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/jamo/combine3': {
      id: '/learn/jamo/combine3'
      path: '/learn/jamo/combine3'
      fullPath: '/learn/jamo/combine3'
      preLoaderRoute: typeof LearnJamoCombine3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/jamo/pronounce': {
      id: '/learn/jamo/pronounce'
      path: '/learn/jamo/pronounce'
      fullPath: '/learn/jamo/pronounce'
      preLoaderRoute: typeof LearnJamoPronounceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/jamo/word-repeat': {
      id: '/learn/jamo/word-repeat'
      path: '/learn/jamo/word-repeat'
      fullPath: '/learn/jamo/word-repeat'
      preLoaderRoute: typeof LearnJamoWordRepeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/jamo/word-write': {
      id: '/learn/jamo/word-write'
      path: '/learn/jamo/word-write'
      fullPath: '/learn/jamo/word-write'
      preLoaderRoute: typeof LearnJamoWordWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/game/': {
      id: '/main/game/'
      path: '/'
      fullPath: '/main/game/'
      preLoaderRoute: typeof MainGameIndexRouteImport
      parentRoute: typeof MainGameRoute
    }
    '/main/game/card-sort': {
      id: '/main/game/card-sort'
      path: '/card-sort'
      fullPath: '/main/game/card-sort'
      preLoaderRoute: typeof MainGameCardSortRouteImport
      parentRoute: typeof MainGameRoute
    }
    '/main/game/missionchat': {
      id: '/main/game/missionchat'
      path: '/missionchat'
      fullPath: '/main/game/missionchat'
      preLoaderRoute: typeof MainGameMissionchatRouteImport
      parentRoute: typeof MainGameRoute
    }
    '/main/game/particle-sniper': {
      id: '/main/game/particle-sniper'
      path: '/particle-sniper'
      fullPath: '/main/game/particle-sniper'
      preLoaderRoute: typeof MainGameParticleSniperRouteImport
      parentRoute: typeof MainGameRoute
    }
    '/main/game/seoul-puzzle': {
      id: '/main/game/seoul-puzzle'
      path: '/seoul-puzzle'
      fullPath: '/main/game/seoul-puzzle'
      preLoaderRoute: typeof MainGameSeoulPuzzleRouteImport
      parentRoute: typeof MainGameRoute
    }
    '/main/game/spring-picnic': {
      id: '/main/game/spring-picnic'
      path: '/spring-picnic'
      fullPath: '/main/game/spring-picnic'
      preLoaderRoute: typeof MainGameSpringPicnicRouteImport
      parentRoute: typeof MainGameRoute
    }
    '/main/game/vocashot': {
      id: '/main/game/vocashot'
      path: '/vocashot'
      fullPath: '/main/game/vocashot'
      preLoaderRoute: typeof MainGameVocashotRouteImport
      parentRoute: typeof MainGameRoute
    }
    '/main/game/vocashot-solo': {
      id: '/main/game/vocashot-solo'
      path: '/vocashot-solo'
      fullPath: '/main/game/vocashot-solo'
      preLoaderRoute: typeof MainGameVocashotSoloRouteImport
      parentRoute: typeof MainGameRoute
    }
    '/main/textbook/': {
      id: '/main/textbook/'
      path: '/'
      fullPath: '/main/textbook/'
      preLoaderRoute: typeof MainTextbookIndexRouteImport
      parentRoute: typeof MainTextbookRoute
    }
    '/main/textbook/jamo': {
      id: '/main/textbook/jamo'
      path: '/jamo'
      fullPath: '/main/textbook/jamo'
      preLoaderRoute: typeof MainTextbookJamoRouteImport
      parentRoute: typeof MainTextbookRoute
    }
    '/book/chapter/unit/$id': {
      id: '/book/chapter/unit/$id'
      path: '/book/chapter/unit/$id'
      fullPath: '/book/chapter/unit/$id'
      preLoaderRoute: typeof BookChapterUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/game/vocashot_/$pin': {
      id: '/main/game/vocashot_/$pin'
      path: '/vocashot/$pin'
      fullPath: '/main/game/vocashot/$pin'
      preLoaderRoute: typeof MainGameVocashotPinRouteImport
      parentRoute: typeof MainGameRoute
    }
    '/book/chapter/unit/dialog/$id': {
      id: '/book/chapter/unit/dialog/$id'
      path: '/book/chapter/unit/dialog/$id'
      fullPath: '/book/chapter/unit/dialog/$id'
      preLoaderRoute: typeof BookChapterUnitDialogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/chapter/unit/flashcard/$id': {
      id: '/book/chapter/unit/flashcard/$id'
      path: '/book/chapter/unit/flashcard/$id'
      fullPath: '/book/chapter/unit/flashcard/$id'
      preLoaderRoute: typeof BookChapterUnitFlashcardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/chapter/unit/input_word/$code': {
      id: '/book/chapter/unit/input_word/$code'
      path: '/book/chapter/unit/input_word/$code'
      fullPath: '/book/chapter/unit/input_word/$code'
      preLoaderRoute: typeof BookChapterUnitInput_wordCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/chapter/unit/listen-repeat/$code': {
      id: '/book/chapter/unit/listen-repeat/$code'
      path: '/book/chapter/unit/listen-repeat/$code'
      fullPath: '/book/chapter/unit/listen-repeat/$code'
      preLoaderRoute: typeof BookChapterUnitListenRepeatCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/chapter/unit/listen-repeat2/$code': {
      id: '/book/chapter/unit/listen-repeat2/$code'
      path: '/book/chapter/unit/listen-repeat2/$code'
      fullPath: '/book/chapter/unit/listen-repeat2/$code'
      preLoaderRoute: typeof BookChapterUnitListenRepeat2CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/chapter/unit/listen/$code': {
      id: '/book/chapter/unit/listen/$code'
      path: '/book/chapter/unit/listen/$code'
      fullPath: '/book/chapter/unit/listen/$code'
      preLoaderRoute: typeof BookChapterUnitListenCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/chapter/unit/make_sentence/$code': {
      id: '/book/chapter/unit/make_sentence/$code'
      path: '/book/chapter/unit/make_sentence/$code'
      fullPath: '/book/chapter/unit/make_sentence/$code'
      preLoaderRoute: typeof BookChapterUnitMake_sentenceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/chapter/unit/mission_chat/$code': {
      id: '/book/chapter/unit/mission_chat/$code'
      path: '/book/chapter/unit/mission_chat/$code'
      fullPath: '/book/chapter/unit/mission_chat/$code'
      preLoaderRoute: typeof BookChapterUnitMission_chatCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/chapter/unit/read-write/$code': {
      id: '/book/chapter/unit/read-write/$code'
      path: '/book/chapter/unit/read-write/$code'
      fullPath: '/book/chapter/unit/read-write/$code'
      preLoaderRoute: typeof BookChapterUnitReadWriteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/chapter/unit/write/$code': {
      id: '/book/chapter/unit/write/$code'
      path: '/book/chapter/unit/write/$code'
      fullPath: '/book/chapter/unit/write/$code'
      preLoaderRoute: typeof BookChapterUnitWriteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/chapter/unit/write2/$code': {
      id: '/book/chapter/unit/write2/$code'
      path: '/book/chapter/unit/write2/$code'
      fullPath: '/book/chapter/unit/write2/$code'
      preLoaderRoute: typeof BookChapterUnitWrite2CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/chapter/unit/write3/$code': {
      id: '/book/chapter/unit/write3/$code'
      path: '/book/chapter/unit/write3/$code'
      fullPath: '/book/chapter/unit/write3/$code'
      preLoaderRoute: typeof BookChapterUnitWrite3CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/chapter/unit/dialog/report/$id': {
      id: '/book/chapter/unit/dialog/report/$id'
      path: '/book/chapter/unit/dialog/report/$id'
      fullPath: '/book/chapter/unit/dialog/report/$id'
      preLoaderRoute: typeof BookChapterUnitDialogReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/chapter/unit/flashcard/result/$id': {
      id: '/book/chapter/unit/flashcard/result/$id'
      path: '/book/chapter/unit/flashcard/result/$id'
      fullPath: '/book/chapter/unit/flashcard/result/$id'
      preLoaderRoute: typeof BookChapterUnitFlashcardResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MainGameRouteChildren {
  MainGameCardSortRoute: typeof MainGameCardSortRoute
  MainGameMissionchatRoute: typeof MainGameMissionchatRoute
  MainGameParticleSniperRoute: typeof MainGameParticleSniperRoute
  MainGameSeoulPuzzleRoute: typeof MainGameSeoulPuzzleRoute
  MainGameSpringPicnicRoute: typeof MainGameSpringPicnicRoute
  MainGameVocashotRoute: typeof MainGameVocashotRoute
  MainGameVocashotSoloRoute: typeof MainGameVocashotSoloRoute
  MainGameIndexRoute: typeof MainGameIndexRoute
  MainGameVocashotPinRoute: typeof MainGameVocashotPinRoute
}

const MainGameRouteChildren: MainGameRouteChildren = {
  MainGameCardSortRoute: MainGameCardSortRoute,
  MainGameMissionchatRoute: MainGameMissionchatRoute,
  MainGameParticleSniperRoute: MainGameParticleSniperRoute,
  MainGameSeoulPuzzleRoute: MainGameSeoulPuzzleRoute,
  MainGameSpringPicnicRoute: MainGameSpringPicnicRoute,
  MainGameVocashotRoute: MainGameVocashotRoute,
  MainGameVocashotSoloRoute: MainGameVocashotSoloRoute,
  MainGameIndexRoute: MainGameIndexRoute,
  MainGameVocashotPinRoute: MainGameVocashotPinRoute,
}

const MainGameRouteWithChildren = MainGameRoute._addFileChildren(
  MainGameRouteChildren,
)

interface MainTextbookRouteChildren {
  MainTextbookJamoRoute: typeof MainTextbookJamoRoute
  MainTextbookIndexRoute: typeof MainTextbookIndexRoute
}

const MainTextbookRouteChildren: MainTextbookRouteChildren = {
  MainTextbookJamoRoute: MainTextbookJamoRoute,
  MainTextbookIndexRoute: MainTextbookIndexRoute,
}

const MainTextbookRouteWithChildren = MainTextbookRoute._addFileChildren(
  MainTextbookRouteChildren,
)

interface MainRouteChildren {
  MainClipRoute: typeof MainClipRoute
  MainGameRoute: typeof MainGameRouteWithChildren
  MainMyRoute: typeof MainMyRoute
  MainTextbookRoute: typeof MainTextbookRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainClipRoute: MainClipRoute,
  MainGameRoute: MainGameRouteWithChildren,
  MainMyRoute: MainMyRoute,
  MainTextbookRoute: MainTextbookRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CheckEmailRoute: CheckEmailRoute,
  FlashcardRoute: FlashcardRoute,
  JamolistRoute: JamolistRoute,
  LoginRoute: LoginRoute,
  MainRoute: MainRouteWithChildren,
  MissionchatRoute: MissionchatRoute,
  MyPasswordRoute: MyPasswordRoute,
  MyProfileRoute: MyProfileRoute,
  NewPasswordRoute: NewPasswordRoute,
  QrRoute: QrRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  BookIdRoute: BookIdRoute,
  BookListRoute: BookListRoute,
  LearnFillBlankRoute: LearnFillBlankRoute,
  LearnGrammarRoute: LearnGrammarRoute,
  LearnListenRoute: LearnListenRoute,
  LearnListenAnswerRoute: LearnListenAnswerRoute,
  LearnReadRoute: LearnReadRoute,
  LearnReadAnswerRoute: LearnReadAnswerRoute,
  LearnRoleplayRoute: LearnRoleplayRoute,
  LearnWordRoute: LearnWordRoute,
  TestIdRoute: TestIdRoute,
  TestAudioRoute: TestAudioRoute,
  TestBoomRoute: TestBoomRoute,
  TestDebugRoute: TestDebugRoute,
  TestFlashcardRoute: TestFlashcardRoute,
  TestRealtimeRoute: TestRealtimeRoute,
  TestTtsRegenRoute: TestTtsRegenRoute,
  TestVideosRoute: TestVideosRoute,
  BookIndexRoute: BookIndexRoute,
  TestIndexRoute: TestIndexRoute,
  BookChapterIdRoute: BookChapterIdRoute,
  LearnJamoChooseRoute: LearnJamoChooseRoute,
  LearnJamoCombineRoute: LearnJamoCombineRoute,
  LearnJamoCombine3Route: LearnJamoCombine3Route,
  LearnJamoPronounceRoute: LearnJamoPronounceRoute,
  LearnJamoWordRepeatRoute: LearnJamoWordRepeatRoute,
  LearnJamoWordWriteRoute: LearnJamoWordWriteRoute,
  BookChapterUnitIdRoute: BookChapterUnitIdRoute,
  BookChapterUnitDialogIdRoute: BookChapterUnitDialogIdRoute,
  BookChapterUnitFlashcardIdRoute: BookChapterUnitFlashcardIdRoute,
  BookChapterUnitInput_wordCodeRoute: BookChapterUnitInput_wordCodeRoute,
  BookChapterUnitListenRepeatCodeRoute: BookChapterUnitListenRepeatCodeRoute,
  BookChapterUnitListenRepeat2CodeRoute: BookChapterUnitListenRepeat2CodeRoute,
  BookChapterUnitListenCodeRoute: BookChapterUnitListenCodeRoute,
  BookChapterUnitMake_sentenceCodeRoute: BookChapterUnitMake_sentenceCodeRoute,
  BookChapterUnitMission_chatCodeRoute: BookChapterUnitMission_chatCodeRoute,
  BookChapterUnitReadWriteCodeRoute: BookChapterUnitReadWriteCodeRoute,
  BookChapterUnitWriteCodeRoute: BookChapterUnitWriteCodeRoute,
  BookChapterUnitWrite2CodeRoute: BookChapterUnitWrite2CodeRoute,
  BookChapterUnitWrite3CodeRoute: BookChapterUnitWrite3CodeRoute,
  BookChapterUnitDialogReportIdRoute: BookChapterUnitDialogReportIdRoute,
  BookChapterUnitFlashcardResultIdRoute: BookChapterUnitFlashcardResultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
