/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QrRouteImport } from './routes/qr'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewPasswordRouteImport } from './routes/new-password'
import { Route as MyWithdrawRouteImport } from './routes/my-withdraw'
import { Route as MyProfileRouteImport } from './routes/my-profile'
import { Route as MyPasswordRouteImport } from './routes/my-password'
import { Route as MainRouteImport } from './routes/main'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainIndexRouteImport } from './routes/main/index'
import { Route as MainTextbookRouteImport } from './routes/main/textbook'
import { Route as MainMyRouteImport } from './routes/main/my'
import { Route as MainGameRouteImport } from './routes/main/game'
import { Route as MainClipRouteImport } from './routes/main/clip'
import { Route as LearnWordRouteImport } from './routes/learn/word'
import { Route as LearnRoleplayRouteImport } from './routes/learn/roleplay'
import { Route as LearnReadAnswerRouteImport } from './routes/learn/read-answer'
import { Route as LearnReadRouteImport } from './routes/learn/read'
import { Route as LearnMissionChatRouteImport } from './routes/learn/mission-chat'
import { Route as LearnListenAnswerRouteImport } from './routes/learn/listen-answer'
import { Route as LearnListenRouteImport } from './routes/learn/listen'
import { Route as LearnJamoRouteImport } from './routes/learn/jamo'
import { Route as LearnGrammarRouteImport } from './routes/learn/grammar'
import { Route as LearnFlashcardRouteImport } from './routes/learn/flashcard'
import { Route as LearnFillBlankRouteImport } from './routes/learn/fill-blank'
import { Route as MainTextbookIndexRouteImport } from './routes/main/textbook/index'
import { Route as MainGameIndexRouteImport } from './routes/main/game/index'
import { Route as MainTextbookJamoRouteImport } from './routes/main/textbook/jamo'
import { Route as MainGameVocashotSoloRouteImport } from './routes/main/game/vocashot-solo'
import { Route as MainGameSpringPicnicRouteImport } from './routes/main/game/spring-picnic'
import { Route as MainGameSeoulPuzzleRouteImport } from './routes/main/game/seoul-puzzle'
import { Route as MainGameParticleSniperRouteImport } from './routes/main/game/particle-sniper'
import { Route as MainGameCardSortRouteImport } from './routes/main/game/card-sort'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPasswordRoute = NewPasswordRouteImport.update({
  id: '/new-password',
  path: '/new-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWithdrawRoute = MyWithdrawRouteImport.update({
  id: '/my-withdraw',
  path: '/my-withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPasswordRoute = MyPasswordRouteImport.update({
  id: '/my-password',
  path: '/my-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainTextbookRoute = MainTextbookRouteImport.update({
  id: '/textbook',
  path: '/textbook',
  getParentRoute: () => MainRoute,
} as any)
const MainMyRoute = MainMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => MainRoute,
} as any)
const MainGameRoute = MainGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => MainRoute,
} as any)
const MainClipRoute = MainClipRouteImport.update({
  id: '/clip',
  path: '/clip',
  getParentRoute: () => MainRoute,
} as any)
const LearnWordRoute = LearnWordRouteImport.update({
  id: '/learn/word',
  path: '/learn/word',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoleplayRoute = LearnRoleplayRouteImport.update({
  id: '/learn/roleplay',
  path: '/learn/roleplay',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnReadAnswerRoute = LearnReadAnswerRouteImport.update({
  id: '/learn/read-answer',
  path: '/learn/read-answer',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnReadRoute = LearnReadRouteImport.update({
  id: '/learn/read',
  path: '/learn/read',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnMissionChatRoute = LearnMissionChatRouteImport.update({
  id: '/learn/mission-chat',
  path: '/learn/mission-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnListenAnswerRoute = LearnListenAnswerRouteImport.update({
  id: '/learn/listen-answer',
  path: '/learn/listen-answer',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnListenRoute = LearnListenRouteImport.update({
  id: '/learn/listen',
  path: '/learn/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnJamoRoute = LearnJamoRouteImport.update({
  id: '/learn/jamo',
  path: '/learn/jamo',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnGrammarRoute = LearnGrammarRouteImport.update({
  id: '/learn/grammar',
  path: '/learn/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnFlashcardRoute = LearnFlashcardRouteImport.update({
  id: '/learn/flashcard',
  path: '/learn/flashcard',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnFillBlankRoute = LearnFillBlankRouteImport.update({
  id: '/learn/fill-blank',
  path: '/learn/fill-blank',
  getParentRoute: () => rootRouteImport,
} as any)
const MainTextbookIndexRoute = MainTextbookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainTextbookRoute,
} as any)
const MainGameIndexRoute = MainGameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainGameRoute,
} as any)
const MainTextbookJamoRoute = MainTextbookJamoRouteImport.update({
  id: '/jamo',
  path: '/jamo',
  getParentRoute: () => MainTextbookRoute,
} as any)
const MainGameVocashotSoloRoute = MainGameVocashotSoloRouteImport.update({
  id: '/vocashot-solo',
  path: '/vocashot-solo',
  getParentRoute: () => MainGameRoute,
} as any)
const MainGameSpringPicnicRoute = MainGameSpringPicnicRouteImport.update({
  id: '/spring-picnic',
  path: '/spring-picnic',
  getParentRoute: () => MainGameRoute,
} as any)
const MainGameSeoulPuzzleRoute = MainGameSeoulPuzzleRouteImport.update({
  id: '/seoul-puzzle',
  path: '/seoul-puzzle',
  getParentRoute: () => MainGameRoute,
} as any)
const MainGameParticleSniperRoute = MainGameParticleSniperRouteImport.update({
  id: '/particle-sniper',
  path: '/particle-sniper',
  getParentRoute: () => MainGameRoute,
} as any)
const MainGameCardSortRoute = MainGameCardSortRouteImport.update({
  id: '/card-sort',
  path: '/card-sort',
  getParentRoute: () => MainGameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-email': typeof CheckEmailRoute
  '/inquiry': typeof InquiryRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRouteWithChildren
  '/my-password': typeof MyPasswordRoute
  '/my-profile': typeof MyProfileRoute
  '/my-withdraw': typeof MyWithdrawRoute
  '/new-password': typeof NewPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/qr': typeof QrRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/learn/fill-blank': typeof LearnFillBlankRoute
  '/learn/flashcard': typeof LearnFlashcardRoute
  '/learn/grammar': typeof LearnGrammarRoute
  '/learn/jamo': typeof LearnJamoRoute
  '/learn/listen': typeof LearnListenRoute
  '/learn/listen-answer': typeof LearnListenAnswerRoute
  '/learn/mission-chat': typeof LearnMissionChatRoute
  '/learn/read': typeof LearnReadRoute
  '/learn/read-answer': typeof LearnReadAnswerRoute
  '/learn/roleplay': typeof LearnRoleplayRoute
  '/learn/word': typeof LearnWordRoute
  '/main/clip': typeof MainClipRoute
  '/main/game': typeof MainGameRouteWithChildren
  '/main/my': typeof MainMyRoute
  '/main/textbook': typeof MainTextbookRouteWithChildren
  '/main/': typeof MainIndexRoute
  '/main/game/card-sort': typeof MainGameCardSortRoute
  '/main/game/particle-sniper': typeof MainGameParticleSniperRoute
  '/main/game/seoul-puzzle': typeof MainGameSeoulPuzzleRoute
  '/main/game/spring-picnic': typeof MainGameSpringPicnicRoute
  '/main/game/vocashot-solo': typeof MainGameVocashotSoloRoute
  '/main/textbook/jamo': typeof MainTextbookJamoRoute
  '/main/game/': typeof MainGameIndexRoute
  '/main/textbook/': typeof MainTextbookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-email': typeof CheckEmailRoute
  '/inquiry': typeof InquiryRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/my-password': typeof MyPasswordRoute
  '/my-profile': typeof MyProfileRoute
  '/my-withdraw': typeof MyWithdrawRoute
  '/new-password': typeof NewPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/qr': typeof QrRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/learn/fill-blank': typeof LearnFillBlankRoute
  '/learn/flashcard': typeof LearnFlashcardRoute
  '/learn/grammar': typeof LearnGrammarRoute
  '/learn/jamo': typeof LearnJamoRoute
  '/learn/listen': typeof LearnListenRoute
  '/learn/listen-answer': typeof LearnListenAnswerRoute
  '/learn/mission-chat': typeof LearnMissionChatRoute
  '/learn/read': typeof LearnReadRoute
  '/learn/read-answer': typeof LearnReadAnswerRoute
  '/learn/roleplay': typeof LearnRoleplayRoute
  '/learn/word': typeof LearnWordRoute
  '/main/clip': typeof MainClipRoute
  '/main/my': typeof MainMyRoute
  '/main': typeof MainIndexRoute
  '/main/game/card-sort': typeof MainGameCardSortRoute
  '/main/game/particle-sniper': typeof MainGameParticleSniperRoute
  '/main/game/seoul-puzzle': typeof MainGameSeoulPuzzleRoute
  '/main/game/spring-picnic': typeof MainGameSpringPicnicRoute
  '/main/game/vocashot-solo': typeof MainGameVocashotSoloRoute
  '/main/textbook/jamo': typeof MainTextbookJamoRoute
  '/main/game': typeof MainGameIndexRoute
  '/main/textbook': typeof MainTextbookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-email': typeof CheckEmailRoute
  '/inquiry': typeof InquiryRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRouteWithChildren
  '/my-password': typeof MyPasswordRoute
  '/my-profile': typeof MyProfileRoute
  '/my-withdraw': typeof MyWithdrawRoute
  '/new-password': typeof NewPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/qr': typeof QrRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/learn/fill-blank': typeof LearnFillBlankRoute
  '/learn/flashcard': typeof LearnFlashcardRoute
  '/learn/grammar': typeof LearnGrammarRoute
  '/learn/jamo': typeof LearnJamoRoute
  '/learn/listen': typeof LearnListenRoute
  '/learn/listen-answer': typeof LearnListenAnswerRoute
  '/learn/mission-chat': typeof LearnMissionChatRoute
  '/learn/read': typeof LearnReadRoute
  '/learn/read-answer': typeof LearnReadAnswerRoute
  '/learn/roleplay': typeof LearnRoleplayRoute
  '/learn/word': typeof LearnWordRoute
  '/main/clip': typeof MainClipRoute
  '/main/game': typeof MainGameRouteWithChildren
  '/main/my': typeof MainMyRoute
  '/main/textbook': typeof MainTextbookRouteWithChildren
  '/main/': typeof MainIndexRoute
  '/main/game/card-sort': typeof MainGameCardSortRoute
  '/main/game/particle-sniper': typeof MainGameParticleSniperRoute
  '/main/game/seoul-puzzle': typeof MainGameSeoulPuzzleRoute
  '/main/game/spring-picnic': typeof MainGameSpringPicnicRoute
  '/main/game/vocashot-solo': typeof MainGameVocashotSoloRoute
  '/main/textbook/jamo': typeof MainTextbookJamoRoute
  '/main/game/': typeof MainGameIndexRoute
  '/main/textbook/': typeof MainTextbookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-email'
    | '/inquiry'
    | '/join'
    | '/login'
    | '/main'
    | '/my-password'
    | '/my-profile'
    | '/my-withdraw'
    | '/new-password'
    | '/privacy'
    | '/qr'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/learn/fill-blank'
    | '/learn/flashcard'
    | '/learn/grammar'
    | '/learn/jamo'
    | '/learn/listen'
    | '/learn/listen-answer'
    | '/learn/mission-chat'
    | '/learn/read'
    | '/learn/read-answer'
    | '/learn/roleplay'
    | '/learn/word'
    | '/main/clip'
    | '/main/game'
    | '/main/my'
    | '/main/textbook'
    | '/main/'
    | '/main/game/card-sort'
    | '/main/game/particle-sniper'
    | '/main/game/seoul-puzzle'
    | '/main/game/spring-picnic'
    | '/main/game/vocashot-solo'
    | '/main/textbook/jamo'
    | '/main/game/'
    | '/main/textbook/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-email'
    | '/inquiry'
    | '/join'
    | '/login'
    | '/my-password'
    | '/my-profile'
    | '/my-withdraw'
    | '/new-password'
    | '/privacy'
    | '/qr'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/learn/fill-blank'
    | '/learn/flashcard'
    | '/learn/grammar'
    | '/learn/jamo'
    | '/learn/listen'
    | '/learn/listen-answer'
    | '/learn/mission-chat'
    | '/learn/read'
    | '/learn/read-answer'
    | '/learn/roleplay'
    | '/learn/word'
    | '/main/clip'
    | '/main/my'
    | '/main'
    | '/main/game/card-sort'
    | '/main/game/particle-sniper'
    | '/main/game/seoul-puzzle'
    | '/main/game/spring-picnic'
    | '/main/game/vocashot-solo'
    | '/main/textbook/jamo'
    | '/main/game'
    | '/main/textbook'
  id:
    | '__root__'
    | '/'
    | '/check-email'
    | '/inquiry'
    | '/join'
    | '/login'
    | '/main'
    | '/my-password'
    | '/my-profile'
    | '/my-withdraw'
    | '/new-password'
    | '/privacy'
    | '/qr'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/learn/fill-blank'
    | '/learn/flashcard'
    | '/learn/grammar'
    | '/learn/jamo'
    | '/learn/listen'
    | '/learn/listen-answer'
    | '/learn/mission-chat'
    | '/learn/read'
    | '/learn/read-answer'
    | '/learn/roleplay'
    | '/learn/word'
    | '/main/clip'
    | '/main/game'
    | '/main/my'
    | '/main/textbook'
    | '/main/'
    | '/main/game/card-sort'
    | '/main/game/particle-sniper'
    | '/main/game/seoul-puzzle'
    | '/main/game/spring-picnic'
    | '/main/game/vocashot-solo'
    | '/main/textbook/jamo'
    | '/main/game/'
    | '/main/textbook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckEmailRoute: typeof CheckEmailRoute
  InquiryRoute: typeof InquiryRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  MainRoute: typeof MainRouteWithChildren
  MyPasswordRoute: typeof MyPasswordRoute
  MyProfileRoute: typeof MyProfileRoute
  MyWithdrawRoute: typeof MyWithdrawRoute
  NewPasswordRoute: typeof NewPasswordRoute
  PrivacyRoute: typeof PrivacyRoute
  QrRoute: typeof QrRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  LearnFillBlankRoute: typeof LearnFillBlankRoute
  LearnFlashcardRoute: typeof LearnFlashcardRoute
  LearnGrammarRoute: typeof LearnGrammarRoute
  LearnJamoRoute: typeof LearnJamoRoute
  LearnListenRoute: typeof LearnListenRoute
  LearnListenAnswerRoute: typeof LearnListenAnswerRoute
  LearnMissionChatRoute: typeof LearnMissionChatRoute
  LearnReadRoute: typeof LearnReadRoute
  LearnReadAnswerRoute: typeof LearnReadAnswerRoute
  LearnRoleplayRoute: typeof LearnRoleplayRoute
  LearnWordRoute: typeof LearnWordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-password': {
      id: '/new-password'
      path: '/new-password'
      fullPath: '/new-password'
      preLoaderRoute: typeof NewPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-withdraw': {
      id: '/my-withdraw'
      path: '/my-withdraw'
      fullPath: '/my-withdraw'
      preLoaderRoute: typeof MyWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-profile': {
      id: '/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-password': {
      id: '/my-password'
      path: '/my-password'
      fullPath: '/my-password'
      preLoaderRoute: typeof MyPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/': {
      id: '/main/'
      path: '/'
      fullPath: '/main/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/textbook': {
      id: '/main/textbook'
      path: '/textbook'
      fullPath: '/main/textbook'
      preLoaderRoute: typeof MainTextbookRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/my': {
      id: '/main/my'
      path: '/my'
      fullPath: '/main/my'
      preLoaderRoute: typeof MainMyRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/game': {
      id: '/main/game'
      path: '/game'
      fullPath: '/main/game'
      preLoaderRoute: typeof MainGameRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/clip': {
      id: '/main/clip'
      path: '/clip'
      fullPath: '/main/clip'
      preLoaderRoute: typeof MainClipRouteImport
      parentRoute: typeof MainRoute
    }
    '/learn/word': {
      id: '/learn/word'
      path: '/learn/word'
      fullPath: '/learn/word'
      preLoaderRoute: typeof LearnWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/roleplay': {
      id: '/learn/roleplay'
      path: '/learn/roleplay'
      fullPath: '/learn/roleplay'
      preLoaderRoute: typeof LearnRoleplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/read-answer': {
      id: '/learn/read-answer'
      path: '/learn/read-answer'
      fullPath: '/learn/read-answer'
      preLoaderRoute: typeof LearnReadAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/read': {
      id: '/learn/read'
      path: '/learn/read'
      fullPath: '/learn/read'
      preLoaderRoute: typeof LearnReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/mission-chat': {
      id: '/learn/mission-chat'
      path: '/learn/mission-chat'
      fullPath: '/learn/mission-chat'
      preLoaderRoute: typeof LearnMissionChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/listen-answer': {
      id: '/learn/listen-answer'
      path: '/learn/listen-answer'
      fullPath: '/learn/listen-answer'
      preLoaderRoute: typeof LearnListenAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/listen': {
      id: '/learn/listen'
      path: '/learn/listen'
      fullPath: '/learn/listen'
      preLoaderRoute: typeof LearnListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/jamo': {
      id: '/learn/jamo'
      path: '/learn/jamo'
      fullPath: '/learn/jamo'
      preLoaderRoute: typeof LearnJamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/grammar': {
      id: '/learn/grammar'
      path: '/learn/grammar'
      fullPath: '/learn/grammar'
      preLoaderRoute: typeof LearnGrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/flashcard': {
      id: '/learn/flashcard'
      path: '/learn/flashcard'
      fullPath: '/learn/flashcard'
      preLoaderRoute: typeof LearnFlashcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/fill-blank': {
      id: '/learn/fill-blank'
      path: '/learn/fill-blank'
      fullPath: '/learn/fill-blank'
      preLoaderRoute: typeof LearnFillBlankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/textbook/': {
      id: '/main/textbook/'
      path: '/'
      fullPath: '/main/textbook/'
      preLoaderRoute: typeof MainTextbookIndexRouteImport
      parentRoute: typeof MainTextbookRoute
    }
    '/main/game/': {
      id: '/main/game/'
      path: '/'
      fullPath: '/main/game/'
      preLoaderRoute: typeof MainGameIndexRouteImport
      parentRoute: typeof MainGameRoute
    }
    '/main/textbook/jamo': {
      id: '/main/textbook/jamo'
      path: '/jamo'
      fullPath: '/main/textbook/jamo'
      preLoaderRoute: typeof MainTextbookJamoRouteImport
      parentRoute: typeof MainTextbookRoute
    }
    '/main/game/vocashot-solo': {
      id: '/main/game/vocashot-solo'
      path: '/vocashot-solo'
      fullPath: '/main/game/vocashot-solo'
      preLoaderRoute: typeof MainGameVocashotSoloRouteImport
      parentRoute: typeof MainGameRoute
    }
    '/main/game/spring-picnic': {
      id: '/main/game/spring-picnic'
      path: '/spring-picnic'
      fullPath: '/main/game/spring-picnic'
      preLoaderRoute: typeof MainGameSpringPicnicRouteImport
      parentRoute: typeof MainGameRoute
    }
    '/main/game/seoul-puzzle': {
      id: '/main/game/seoul-puzzle'
      path: '/seoul-puzzle'
      fullPath: '/main/game/seoul-puzzle'
      preLoaderRoute: typeof MainGameSeoulPuzzleRouteImport
      parentRoute: typeof MainGameRoute
    }
    '/main/game/particle-sniper': {
      id: '/main/game/particle-sniper'
      path: '/particle-sniper'
      fullPath: '/main/game/particle-sniper'
      preLoaderRoute: typeof MainGameParticleSniperRouteImport
      parentRoute: typeof MainGameRoute
    }
    '/main/game/card-sort': {
      id: '/main/game/card-sort'
      path: '/card-sort'
      fullPath: '/main/game/card-sort'
      preLoaderRoute: typeof MainGameCardSortRouteImport
      parentRoute: typeof MainGameRoute
    }
  }
}

interface MainGameRouteChildren {
  MainGameCardSortRoute: typeof MainGameCardSortRoute
  MainGameParticleSniperRoute: typeof MainGameParticleSniperRoute
  MainGameSeoulPuzzleRoute: typeof MainGameSeoulPuzzleRoute
  MainGameSpringPicnicRoute: typeof MainGameSpringPicnicRoute
  MainGameVocashotSoloRoute: typeof MainGameVocashotSoloRoute
  MainGameIndexRoute: typeof MainGameIndexRoute
}

const MainGameRouteChildren: MainGameRouteChildren = {
  MainGameCardSortRoute: MainGameCardSortRoute,
  MainGameParticleSniperRoute: MainGameParticleSniperRoute,
  MainGameSeoulPuzzleRoute: MainGameSeoulPuzzleRoute,
  MainGameSpringPicnicRoute: MainGameSpringPicnicRoute,
  MainGameVocashotSoloRoute: MainGameVocashotSoloRoute,
  MainGameIndexRoute: MainGameIndexRoute,
}

const MainGameRouteWithChildren = MainGameRoute._addFileChildren(
  MainGameRouteChildren,
)

interface MainTextbookRouteChildren {
  MainTextbookJamoRoute: typeof MainTextbookJamoRoute
  MainTextbookIndexRoute: typeof MainTextbookIndexRoute
}

const MainTextbookRouteChildren: MainTextbookRouteChildren = {
  MainTextbookJamoRoute: MainTextbookJamoRoute,
  MainTextbookIndexRoute: MainTextbookIndexRoute,
}

const MainTextbookRouteWithChildren = MainTextbookRoute._addFileChildren(
  MainTextbookRouteChildren,
)

interface MainRouteChildren {
  MainClipRoute: typeof MainClipRoute
  MainGameRoute: typeof MainGameRouteWithChildren
  MainMyRoute: typeof MainMyRoute
  MainTextbookRoute: typeof MainTextbookRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainClipRoute: MainClipRoute,
  MainGameRoute: MainGameRouteWithChildren,
  MainMyRoute: MainMyRoute,
  MainTextbookRoute: MainTextbookRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckEmailRoute: CheckEmailRoute,
  InquiryRoute: InquiryRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  MainRoute: MainRouteWithChildren,
  MyPasswordRoute: MyPasswordRoute,
  MyProfileRoute: MyProfileRoute,
  MyWithdrawRoute: MyWithdrawRoute,
  NewPasswordRoute: NewPasswordRoute,
  PrivacyRoute: PrivacyRoute,
  QrRoute: QrRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  LearnFillBlankRoute: LearnFillBlankRoute,
  LearnFlashcardRoute: LearnFlashcardRoute,
  LearnGrammarRoute: LearnGrammarRoute,
  LearnJamoRoute: LearnJamoRoute,
  LearnListenRoute: LearnListenRoute,
  LearnListenAnswerRoute: LearnListenAnswerRoute,
  LearnMissionChatRoute: LearnMissionChatRoute,
  LearnReadRoute: LearnReadRoute,
  LearnReadAnswerRoute: LearnReadAnswerRoute,
  LearnRoleplayRoute: LearnRoleplayRoute,
  LearnWordRoute: LearnWordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
